import Header from './component/header'
import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="max-w-5xl mx-auto">
        <Header />
        {children}

      </body>
    </html>
  )
}
